### ISSUE TITLE
[Settings] Set Engine Icon to Project's Avatar

### ISSUE THREAD

**Issue by kevinmatthes** [StarSimVR/godot#2]
GitHub automatically assigns avatars to newly created accounts and organisations.  In case of ours, I think, the randomly assigned icon fits the topic of our project, a simulation of astronomic objects, very well since it looks like an alien somehow.  Nevertheless, we might also change it in case you should really dislike it, @Luka-sama.

I would like to ask you to adjust the engine's settings such that the used icon (`./icon.png`) is set the current avatar of our project.  Shall I therefore check in the current avatar of this namespace as a PNG?

**Comment by Luka-sama** [comment]
Okay, I changed the icon. I also created an ico file for Windows.
