### ISSUE TITLE
Class properties using custom data types

### ISSUE THREAD

**Issue by NiklasLeukroth** [StarSimVR/godot#6]
In godot, every advanced or custom data type is a problem as a member variable. 
For example std::vector<float> or Rnfpp cannot be used as a member variable, because godot can't handle them and therefor tries to cast them to a Variant class: https://docs.godotengine.org/de/stable/classes/class_variant.html
This cast is not defined, therefore the compilation breaks.

I think we therefore have to use the Vector3 Class, provided by godot. Luckily this class already comes with a lot of built-in functionality, so that a migration from Rnfpp to Vector3 should be quiet easy.

However, if there is another way, which may be better or more elegant, i would be happy to learn about it.

**Comment by kevinmatthes** [comment]
Did you try to just implement a cast from `Rnfpp` to `Vector3`, @Ranplax?

**Comment by kevinmatthes** [comment]
I think the suggested solution to rely on the built-in type would be the most efficient option.
